export const Heroes = [
    { id: 1, nombre: 'Super Candela', fechaNacimiento: '01/01/1990', habilidades: "Fuego", sexo: "masculino", origen: "Heroe urbano de Villavicencio. Surgio en un asado", debilidades: "Lluvia, Maicena.", relacionesPersonales: ['Chico Chispa'] },
    { id: 2, nombre: 'Chico Chispa', fechaNacimiento: '01/01/2002', habilidades: "Fueguito", sexo: "masculino", origen: "Nacido en los confines de un pequeño pueblo rodeado por densos bosques", debilidades: "Agua", relacionesPersonales: ['Super Candela'] },
    { id: 3, nombre: 'Electra', fechaNacimiento: '05/15/1985', habilidades: "Control eléctrico", sexo: "femenino", origen: "Ingeniera eléctrica expuesta a un experimento", debilidades: "Aislantes", relacionesPersonales: ['Super Candela', 'Fénix']},
    { id: 4, nombre: 'Capitán Escudo', fechaNacimiento: '03/20/1988', habilidades: "Manejo experto de escudo", sexo: "masculino", origen: "Soldado con habilidades tácticas avanzadas", debilidades: "Imanes", relacionesPersonales: ['Señor Viento', 'Fénix', 'Lady Llave']},
    { id: 5, nombre: 'Sombra Veloz', fechaNacimiento: '07/07/1995', habilidades: "Teletransportación", sexo: "femenino", origen: "Experimento de teletransportación en laboratorio secreto", debilidades: "Distancias extremas", relacionesPersonales: ['Dama de Hielo']},
    { id: 6, nombre: 'Fénix', fechaNacimiento: '11/11/1980', habilidades: "Regeneración y control del fuego", sexo: "femenino", origen: "Mutación genética", debilidades: "Agua fría", relacionesPersonales: ['Chisco chispa']},
    { id: 7, nombre: 'Dr. Gravedad', fechaNacimiento: '09/30/1975', habilidades: "Manipulación de la gravedad", sexo: "masculino", origen: "Físico cuántico expuesto a radiación", debilidades: "Anti-gravedad", relacionesPersonales: ['Furia Bestial', 'Química Cerebral']},
    { id: 8, nombre: 'Luz Estelar', fechaNacimiento: '02/14/1983', habilidades: "Control de la luz y energía estelar", sexo: "femenino", origen: "Conexión cósmica", debilidades: "Oscuridad absoluta", relacionesPersonales: ['Furia Bestial', 'Química Cerebral']},
    { id: 9, nombre: 'El Invisiblón', fechaNacimiento: '06/25/1992', habilidades: "Invisibilidad", sexo: "masculino", origen: "Accidente con sustancia experimental", debilidades: "Polvo revelador", relacionesPersonales: ['Furia Bestial', 'Química Cerebral']},
    { id: 10, nombre: 'Magnetico', fechaNacimiento: '12/05/1987', habilidades: "Manipulación magnética", sexo: "masculino", origen: "Científico con exposición a campos magnéticos", debilidades: "Campo magnético inverso", relacionesPersonales: ['Sombra Veloz']},
    { id: 11, nombre: 'Dama de Hielo', fechaNacimiento: '04/18/1998', habilidades: "Control del hielo", sexo: "femenino", origen: "Princesa de una tierra helada", debilidades: "Fuego", relacionesPersonales: ['Magnetico', 'Dr. Gravedad']},
    { id: 12, nombre: 'El Centelleante', fechaNacimiento: '08/08/1986', habilidades: "Super velocidad", sexo: "masculino", origen: "Explosión de energía cósmica", debilidades: "Desaceleración temporal", relacionesPersonales: ['Super Candela']},
    { id: 13, nombre: 'Lady Llave', fechaNacimiento: '03/03/1993', habilidades: "Manipulación de cerraduras y puertas", sexo: "femenino", origen: "Hija de un cerrajero prodigio", debilidades: "Cerraduras de alta seguridad", relacionesPersonales: ['Super Candela']},
    { id: 14, nombre: 'La Mente Brillante', fechaNacimiento: '10/20/1980', habilidades: "Telequinesis", sexo: "masculino", origen: "Experimento gubernamental", debilidades: "Bloqueo mental", relacionesPersonales: ['Fénix, Señor Viento']},
    { id: 15, nombre: 'Furia Bestial', fechaNacimiento: '06/15/1995', habilidades: "Transformación en bestia", sexo: "masculino", origen: "Maldición ancestral", debilidades: "Calma extrema", relacionesPersonales: ['Sombra Veloz']},
    { id: 16, nombre: 'Señor Viento', fechaNacimiento: '09/22/1984', habilidades: "Control del viento", sexo: "masculino", origen: "Monje en la cima de una montaña", debilidades: "Aire inmóvil", relacionesPersonales: ['Capitán Escudo']},
    { id: 17, nombre: 'Química Cerebral', fechaNacimiento: '07/12/1990', habilidades: "Manipulación química mental", sexo: "femenino", origen: "Científica de la mente", debilidades: "Escudos psíquicos", relacionesPersonales: ['Dr. Gravedad']},
    { id: 18, nombre: 'Sombrío', fechaNacimiento: '11/30/1989', habilidades: "Control de las sombras", sexo: "masculino", origen: "Experimento con dimensiones oscuras", debilidades: "Luz intensa", relacionesPersonales: ['Dama de Hielo']},
    { id: 19, nombre: 'Mente Maestra', fechaNacimiento: '12/10/1982', habilidades: "Telepatía", sexo: "femenino", origen: "Experimento de laboratorio", debilidades: "Ruido intenso", relacionesPersonales: ['Lady Llave']},
    { id: 20, nombre: 'Cibernético', fechaNacimiento: '04/02/2000', habilidades: "Mejoras cibernéticas", sexo: "masculino", origen: "Humano mejorado con tecnología avanzada", debilidades: "Hacker experto", relacionesPersonales: ['Mente Maestra']}
  ];
export const Villanos = [
    { id: 1, nombre: 'Piro Sombra', fechaNacimiento: '02/02/1992', habilidades: "Manipulación de fuego oscuro", sexo: "masculino", origen: "Experimento de sombras ígneas", debilidades: "Luz brillante" },
    { id: 2, nombre: 'Voltio Negro', fechaNacimiento: '01/01/1992', habilidades: "Descargas eléctricas letales", sexo: "masculino", origen: "Ingeniero desquiciado por la electricidad", debilidades: "Aislantes mejorados" },
    { id: 3, nombre: 'Dama Escarlata', fechaNacimiento: '09/09/1999', habilidades: "Escudo místico y control mental", sexo: "femenino", origen: "Bruja con sed de venganza", debilidades: "Voluntad extrema" },
    { id: 4, nombre: 'El Destructor Magnético', fechaNacimiento: '03/05/1985', habilidades: "Desastres magnéticos a gran escala", sexo: "masculino", origen: "Científico corrompido por el poder", debilidades: "Magnetismo inverso a nivel cósmico" },
    { id: 5, nombre: 'Espectro Gélido', fechaNacimiento: '11/11/1988', habilidades: "Creación y control de hielo letal", sexo: "femenino", origen: "Experimento congelante fallido", debilidades: "Calor extremo" },
    { id: 6, nombre: 'Nébula Veloz', fechaNacimiento: '07/03/1996', habilidades: "Teletransportación interdimensional", sexo: "masculino", origen: "Viajero interdimensional corrupto", debilidades: "Inestabilidad dimensional" },
    { id: 7, nombre: 'Gravedad Oscura', fechaNacimiento: '12/12/1980', habilidades: "Manipulación gravitacional destructiva", sexo: "femenino", origen: "Científica caída en la oscuridad", debilidades: "Anti-materia" },
    { id: 8, nombre: 'Luna Negra', fechaNacimiento: '06/06/1976', habilidades: "Control de energía lunar corrupta", sexo: "femenino", origen: "Hechicera lunar desterrada", debilidades: "Luz lunar purificadora" },
    { id: 9, nombre: 'El Invisible', fechaNacimiento: '04/09/1983', habilidades: "Invisibilidad avanzada y sabotaje", sexo: "masculino", origen: "Exespía con tecnología de invisibilidad", debilidades: "Sensores de detección mejorados" },
    { id: 10, nombre: 'Psycho Químico', fechaNacimiento: '08/07/1979', habilidades: "Manipulación psicodélica", sexo: "masculino", origen: "Alquimista mental desequilibrado", debilidades: "Estabilidad emocional" },
    { id: 11, nombre: 'Sombra Mortal', fechaNacimiento: '05/10/1995', habilidades: "Creación y control de sombras asesinas", sexo: "femenino", origen: "Entidad oscura liberada por error", debilidades: "Luz celestial" },
    { id: 12, nombre: 'Rey de la Desaceleración', fechaNacimiento: '02/04/1988', habilidades: "Ralentización temporal", sexo: "masculino", origen: "Viajero del tiempo corrupto", debilidades: "Aceleración temporal" },
    { id: 13, nombre: 'Ladrón de Almas', fechaNacimiento: '09/01/1990', habilidades: "Robo y manipulación de almas", sexo: "femenino", origen: "Entidad demoníaca posesora", debilidades: "Poder divino" },
    { id: 14, nombre: 'Ciclón Devastador', fechaNacimiento: '03/08/1982', habilidades: "Control de vientos mortales", sexo: "masculino", origen: "Hechicero expulsado por la naturaleza", debilidades: "Calma total" },
    { id: 15, nombre: 'Química Mental', fechaNacimiento: '10/06/1973', habilidades: "Manipulación química cerebral", sexo: "femenino", origen: "Científica rival de Química Cerebral", debilidades: "Bloqueo químico" },
    { id: 16, nombre: 'Umbral Sombrío', fechaNacimiento: '11/09/1998', habilidades: "Apertura de portales sombríos", sexo: "masculino", origen: "Explorador de dimensiones prohibidas", debilidades: "Luz dimensional" },
    { id: 17, nombre: 'Sirena de Pensamientos', fechaNacimiento: '07/02/1986', habilidades: "Control mental y lectura de mentes", sexo: "femenino", origen: "Víctima de experimento gubernamental", debilidades: "Resistencia psíquica" },
    { id: 18, nombre: 'Cibernauta Malévolo', fechaNacimiento: '01/03/1984', habilidades: "Hacking letal y control de tecnología", sexo: "masculino", origen: "Criminal cibernético mejorado", debilidades: "IA antihacker" },
    { id: 19, nombre: 'Fuego Negro', fechaNacimiento: '05/07/1993', habilidades: "Manipulación de llamas corruptas", sexo: "femenino", origen: "Entidad ígnea caída en desgracia", debilidades: "Agua bendita" },
    { id: 20, nombre: 'Máquina Asesina', fechaNacimiento: '12/10/1987', habilidades: "Asesinato sin emociones y fuerza sobrehumana", sexo: "masculino", origen: "Humano modificado por inteligencia artificial", debilidades: "Empatía humana" }
];
export const Patrocinadores = [
  { id: 1, nombre: 'Bill Jet', monto: 100_000_000, heroeId: 1, fuenteDinero: 'Una gran empresa farmaceutica.'},
  { id: 2, nombre: 'Tech Innovations', monto: 80_000_000, heroeId: 2, fuenteDinero: 'Empresa de tecnología avanzada.'},
  { id: 3, nombre: 'Power Solutions', monto: 120_000_000, heroeId: 3, fuenteDinero: 'Corporación energética.'},
  { id: 4, nombre: 'Defense Systems', monto: 150_000_000, heroeId: 4, fuenteDinero: 'Contratista de defensa militar.'},
  { id: 5, nombre: 'Teleport Tech', monto: 90_000_000, heroeId: 5, fuenteDinero: 'Empresa de investigación en teletransportación.'},
  { id: 6, nombre: 'Phoenix Genetics', monto: 110_000_000, heroeId: 6, fuenteDinero: 'Centro de investigación genética.'},
  { id: 7, nombre: 'Gravity Dynamics', monto: 130_000_000, heroeId: 7, fuenteDinero: 'Empresa especializada en manipulación de la gravedad.'},
  { id: 8, nombre: 'Stellar Illumination', monto: 100_000_000, heroeId: 8, fuenteDinero: 'Corporación cósmica de energía estelar.'},
  { id: 9, nombre: 'Invisible Tech', monto: 85_000_000, heroeId: 9, fuenteDinero: 'Empresa de desarrollo de tecnología de invisibilidad.'},
  { id: 10, nombre: 'Magnetic Innovations', monto: 95_000_000, heroeId: 10, fuenteDinero: 'Laboratorio de investigación magnética.'},
  { id: 11, nombre: 'Frozen Kingdom', monto: 120_000_000, heroeId: 11, fuenteDinero: 'Corporación de tecnología de hielo.'},
  { id: 12, nombre: 'Cosmic Velocity', monto: 110_000_000, heroeId: 12, fuenteDinero: 'Instituto de investigación espacial.'},
  { id: 13, nombre: 'Locksmith Prodigy', monto: 75_000_000, heroeId: 13, fuenteDinero: 'Empresa de seguridad y cerrajería.'},
  { id: 14, nombre: 'Mind Control Corp', monto: 140_000_000, heroeId: 14, fuenteDinero: 'Corporación gubernamental de telequinesis.'},
  { id: 15, nombre: 'Beastly Transformations', monto: 160_000_000, heroeId: 15, fuenteDinero: 'Empresa de investigación en transformaciones animales.'},
  { id: 16, nombre: 'Wind Mastery', monto: 95_000_000, heroeId: 16, fuenteDinero: 'Monasterio de control del viento.'},
  { id: 17, nombre: 'Psychic Chemistry', monto: 120_000_000, heroeId: 17, fuenteDinero: 'Laboratorio de manipulación química mental.'},
  { id: 18, nombre: 'Shadow Technologies', monto: 80_000_000, heroeId: 18, fuenteDinero: 'Empresa de investigación en control de sombras.'},
  { id: 19, nombre: 'Mindlink Experiment', monto: 100_000_000, heroeId: 19, fuenteDinero: 'Laboratorio de experimentos de telepatía.'},
  { id: 20, nombre: 'Cybernetic Enhancements', monto: 130_000_000, heroeId: 20, fuenteDinero: 'Corporación de mejoras cibernéticas.'},
  { id: 21, nombre: 'Lunar Mining Corp', monto: 110_000_000, heroeId: 1, fuenteDinero: 'Corporación minera lunar.'},
  { id: 22, nombre: 'Nanotech Innovations', monto: 85_000_000, heroeId: 2, fuenteDinero: 'Empresa de nanotecnología.'},
  { id: 23, nombre: 'Solar Energy Solutions', monto: 120_000_000, heroeId: 3, fuenteDinero: 'Proveedor de soluciones de energía solar.'},
  { id: 24, nombre: 'Aero Dynamics', monto: 150_000_000, heroeId: 4, fuenteDinero: 'Empresa de tecnología aeroespacial.'},
  { id: 25, nombre: 'Quantum Computing Co.', monto: 90_000_000, heroeId: 5, fuenteDinero: 'Compañía de computación cuántica.'},
  { id: 26, nombre: 'Bio-Regeneration Labs', monto: 110_000_000, heroeId: 6, fuenteDinero: 'Laboratorios de bio-regeneración.'},
  { id: 27, nombre: 'Anti-Gravity Innovations', monto: 130_000_000, heroeId: 7, fuenteDinero: 'Empresa de innovaciones antigravedad.'},
  { id: 28, nombre: 'Celestial Technologies', monto: 100_000_000, heroeId: 8, fuenteDinero: 'Tecnologías celestiales avanzadas.'},
  { id: 29, nombre: 'Stealth Tech Solutions', monto: 85_000_000, heroeId: 9, fuenteDinero: 'Soluciones tecnológicas de sigilo.'},
  { id: 30, nombre: 'Magnetic Levitation Inc.', monto: 95_000_000, heroeId: 10, fuenteDinero: 'Empresa de levitación magnética.'},
];
export const Horarios = [
    { id: 1, nombre: 'Super Candela', diasActivos: ['Lunes', 'Martes', 'Miércoles', 'Viernes'], horasActivas: ['6:00AM-10:00AM', '5:00PM-8:15PM'] },
    { id: 2, nombre: 'Chico Chispa', diasActivos: ['Martes', 'Jueves', 'Sábado'], horasActivas: ['4:30PM-7:45PM', '9:00AM-11:30AM'] },
    { id: 3, nombre: 'Electra', diasActivos: ['Lunes', 'Miércoles', 'Viernes'], horasActivas: ['3:00PM-6:30PM', '9:00AM-12:00PM'] },
    { id: 4, nombre: 'Capitán Escudo', diasActivos: ['Lunes', 'Miércoles', 'Viernes'], horasActivas: ['7:00AM-10:00AM', '4:30PM-7:00PM'] },
    { id: 5, nombre: 'Sombra Veloz', diasActivos: ['Martes', 'Jueves', 'Sábado'], horasActivas: ['6:15PM-9:00PM', '10:30AM-1:00PM'] },
    { id: 6, nombre: 'Fénix', diasActivos: ['Lunes', 'Miércoles', 'Viernes'], horasActivas: ['8:00AM-11:00AM', '7:00PM-10:00PM'] },
    { id: 7, nombre: 'Dr. Gravedad', diasActivos: ['Lunes', 'Miércoles', 'Viernes'], horasActivas: ['2:30PM-5:30PM', '8:00PM-10:30PM'] },
    { id: 8, nombre: 'Luz Estelar', diasActivos: ['Martes', 'Jueves', 'Sábado'], horasActivas: ['5:30PM-8:00PM', '11:00AM-1:30PM'] },
    { id: 9, nombre: 'El Invisiblón', diasActivos: ['Lunes', 'Miércoles', 'Viernes'], horasActivas: ['6:45AM-9:30AM', '3:30PM-6:45PM'] },
    { id: 10, nombre: 'Magnetico', diasActivos: ['Martes', 'Jueves', 'Sábado'], horasActivas: ['8:30AM-11:45AM', '6:00PM-9:00PM'] },
    { id: 11, nombre: 'Dama de Hielo', diasActivos: ['Lunes', 'Miércoles', 'Viernes'], horasActivas: ['4:00PM-7:00PM', '10:00AM-12:30PM'] },
    { id: 12, nombre: 'El Centelleante', diasActivos: ['Martes', 'Jueves', 'Sábado'], horasActivas: ['7:15AM-10:30AM', '4:45PM-7:15PM'] },
    { id: 13, nombre: 'Lady Llave', diasActivos: ['Lunes', 'Miércoles', 'Viernes'], horasActivas: ['5:15PM-8:30PM', '11:30AM-2:00PM'] },
    { id: 14, nombre: 'La Mente Brillante', diasActivos: ['Martes', 'Jueves', 'Sábado'], horasActivas: ['3:45PM-7:00PM', '9:30AM-12:45PM'] },
    { id: 15, nombre: 'Furia Bestial', diasActivos: ['Lunes', 'Miércoles', 'Viernes'], horasActivas: ['8:45AM-11:15AM', '6:15PM-9:30PM'] },
    { id: 16, nombre: 'Señor Viento', diasActivos: ['Martes', 'Jueves', 'Sábado'], horasActivas: ['2:00PM-5:00PM', '7:30PM-10:00PM'] },
    { id: 17, nombre: 'Química Cerebral', diasActivos: ['Lunes', 'Miércoles', 'Viernes'], horasActivas: ['5:30PM-8:00PM', '10:00AM-1:00PM'] },
    { id: 18, nombre: 'Sombrío', diasActivos: ['Martes', 'Jueves', 'Sábado'], horasActivas: ['7:30AM-10:45AM', '4:00PM-6:30PM'] },
    { id: 19, nombre: 'Mente Maestra', diasActivos: ['Lunes', 'Miércoles', 'Viernes'], horasActivas: ['4:30PM-7:30PM', '9:15AM-11:45AM'] },
    { id: 20, nombre: 'Cibernético', diasActivos: ['Martes', 'Jueves', 'Sábado'], horasActivas: ['6:30PM-9:45PM', '8:00AM-11:00AM'] },
  ];
  export const Luchas = [
    { id: 2, heroes: ['Fénix', 'Capitán Escudo'], villanos: ['Ciclón Devastador'], resultado: "victoria" },
    { id: 3, heroes: ['Dr. Gravedad', 'Dama de Hielo'], villanos: ['Gravedad Oscura'], resultado: "derrota" },
    { id: 4, heroes: ['Luz Estelar', 'Señor Viento'], villanos: ['Nébula Veloz'], resultado: "victoria" },
    { id: 5, heroes: ['Magnetico', 'El Invisiblón'], villanos: ['Umbral Sombrío'], resultado: "derrota" },
    { id: 6, heroes: ['El Centelleante', 'Lady Llave'], villanos: ['Ladrón de Almas'], resultado: "victoria" },
    { id: 7, heroes: ['La Mente Brillante', 'Furia Bestial'], villanos: ['Psycho Químico'], resultado: "derrota" },
    { id: 8, heroes: ['Señor Viento', 'Química Cerebral'], villanos: ['Sirena de Pensamientos'], resultado: "victoria" },
    { id: 9, heroes: ['Sombrío', 'Cibernético'], villanos: ['Rey de la Desaceleración'], resultado: "derrota" },
    { id: 10, heroes: ['Mente Maestra', 'Super Candela'], villanos: ['Voltio Negro'], resultado: "victoria" },
    { id: 11, heroes: ['Chico Chispa', 'Fénix'], villanos: ['Espectro Gélido'], resultado: "derrota" },
  ];
  